apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoid29vY2hhbjI3NTYiLCJwYXNzd29yZCI6ImdocF9oN2pNbHJmVUR0V2piS3BmbUJLQmJyOHJodVJXRlYyaThkeloiLCJlbWFpbCI6Indvb2NoYW4yNzU2QGdtYWlsLmNvbSIsImF1dGgiOiJkMjl2WTJoaGJqSTNOVFk2WjJod1gyZzNhazFzY21aVlJIUlhhbUpMY0dadFFrdENZbkk0Y21oMVVsZEdWakpwT0dSNldnPT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: woochan2756
type: kubernetes.io/dockerconfigjson
